# Generated by Django 2.1.1 on 2023-04-15 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('BranchName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('Capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
                ('EmployeeName', models.CharField(max_length=200)),
                ('EmployeePhone', models.IntegerField()),
                ('EmployeePosition', models.CharField(max_length=100)),
                ('Salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PassengerName', models.CharField(max_length=200)),
                ('PassengerPhone', models.IntegerField()),
                ('SeatNumber', models.IntegerField()),
                ('Price', models.FloatField()),
                ('Payment', models.CharField(max_length=200)),
                ('DateOfPurchase', models.DateTimeField()),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('StartPoint', models.CharField(max_length=100)),
                ('StartDate', models.DateTimeField()),
                ('EndPoint', models.CharField(max_length=100)),
                ('EndDate', models.DateTimeField()),
                ('busId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTapp.Bus')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='tripId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTapp.Trip'),
        ),
        migrations.AddField(
            model_name='branch',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTapp.Employee'),
        ),
    ]
