# Generated by Django 2.1.1 on 2023-04-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
